MySql:
   host: "localhost"
   port: 3306
   database: "db"
   user: "root"
   password: "password"
Rollback:
  OnQuit: false
  OnChangeWorld: false
  OnGameModechange: true
PastebinKey: "" # You will have to create a pastebin account and get your developer key from https://pastebin.com/api#1
TFAExpiration: 8.64e+7 #1 Day